name: set up boost
description: Ensures boost is available

inputs:
  version:
    description: 'Exact version to install (example: 1.75.0)'
    required: true

runs:
  using: composite
  steps:
    - name: Locate a suitable BOOST_ROOT
      id: boost-root
      shell: bash
      run: |
        if [ "${{ runner.os }}" == Windows ]
        then
          echo "::set-output name=path::C:\\.boost\\${{ inputs.version }}"
        elif [ "${{ runner.os }}" == macOS ]
        then
          echo "::set-output name=path::${HOME}/.boost/${{ inputs.version }}"
        else
          echo "::set-output name=path::${HOME}/.boost/${{ inputs.version }}"
        fi

    - name: Update environment variables
      shell: bash
      run: |
        echo "BOOST_ROOT=${{ steps.boost-root.outputs.path }}" >> $GITHUB_ENV
        echo "BOOST_BUILD_PATH=${{ steps.boost-root.outputs.path }}/tools/build" >> $GITHUB_ENV
        echo "${{ steps.boost-root.outputs.path }}" >> $GITHUB_PATH

    - name: Load boost from cache
      id: cache
      uses: actions/cache@v2
      with:
        key: boost-${{ inputs.version }}-${{ runner.os }}
        path: ${{ steps.boost-root.outputs.path }}

    - name: Download and install boost
      shell: bash
      run: |
        if [ "${{ steps.cache.outputs.cache-hit }}" == true ]
        then
          echo "::debug::Cache hit, skipping install"
        else
          ${{ github.action_path }}/setup_boost.sh "${{ inputs.version }}" "${{ steps.boost-root.outputs.path }}"
        fi
